# Generated by Django 4.1 on 2022-09-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ('-descripcion',), 'verbose_name': 'Categoria producto', 'verbose_name_plural': 'Categorias productos'},
        ),
        migrations.AlterModelOptions(
            name='linea',
            options={'ordering': ('-descripcion',), 'verbose_name': 'Linea producto', 'verbose_name_plural': 'Lineas productos'},
        ),
        migrations.AlterField(
            model_name='grupo',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.linea'),
        ),
    ]
